name: Test verify

on:
  push:

jobs:
  test_validation:
    name: "Test Verify"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Submodules update
        run: make update

      - name: Test verify
        run: make test

  build_validation:
    name: "Build Verify"
    runs-on: ubuntu-latest
    needs:
      - test_validation
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Submodules update
        run: make update

      - name: Build verify
        run: make build
